### ISSUE TITLE
亲爱的作者，能否提供安装的教程和使用说明？

### ISSUE THREAD

**Issue by linfanmz** [but0n/JianSo_Movie#28]
没有太能够理解wsgi的内容，在尝试运行的过程中也出现了诸多的问题。希望作者君能够提供一个简单的安装教程和说明。感谢

**Comment by but0n** [comment]
Clone 项目到本地
```
$ git clone https://github.com/but0n/JianSo_Movie
```
安装bs4
```
$ sudo pip install beautifulsoup4
```
安装request
```
$ sudo pip install requests
```

然后就可以愉快的爬电影资源了
```
$ python robot.py
```
这个爬虫会爬取电影, 电影的下载地址, 电影的海报地址, 电影的介绍并保存到`mv.db`

因为这里仅仅是爬去了电影海报的地址, 所以还需要运行一个脚本来批量下载
```
$ cd static/images 
```
```
$ python Get_img.py
```
*刚才试了试, 这个现在用不了, 图片地址有点问题, 需要修改`robot.py`*


* *如果在本地搭建的话不需要wsgi, 使用Flask自带的http服务器也是可以的*

### 在local开启web服务

先安装`Flask`
```
$ sudo pip install flask
```
然后运行
```
$ python hello.py
```
然后用浏览器访问 http://127.0.0.1:5000 试试

**Comment by linfanmz** [comment]
好的。谢谢，我在尝试学习在抓取电影内容的同时，抓取演职员表，内容简介等信息，并合并到一个页面。试试看~~作者君辛苦啦

**Comment by linfanmz** [comment]
好的。谢谢，我在尝试学习在抓取电影内容的同时，抓取演职员表，内容简介等信息，并合并到一个页面。试试看~~作者君辛苦啦

**Comment by linfanmz** [comment]
好的。谢谢，我在尝试学习在抓取电影内容的同时，抓取演职员表，内容简介等信息，并合并到一个页面。试试看~~作者君辛苦啦

**Comment by linfanmz** [comment]
好的。谢谢，我在尝试学习在抓取电影内容的同时，抓取演职员表，内容简介等信息，并合并到一个页面。试试看~~作者君辛苦啦

**Comment by linfanmz** [comment]
好的。谢谢，我在尝试学习在抓取电影内容的同时，抓取演职员表，内容简介等信息，并合并到一个页面。试试看~~作者君辛苦啦

**Comment by linfanmz** [comment]
好的。谢谢，我在尝试学习在抓取电影内容的同时，抓取演职员表，内容简介等信息，并合并到一个页面。试试看~~作者君辛苦啦

**Comment by linfanmz** [comment]
好的。谢谢，我在尝试学习在抓取电影内容的同时，抓取演职员表，内容简介等信息，并合并到一个页面。试试看~~作者君辛苦啦

**Comment by linfanmz** [comment]
好的。谢谢，我在尝试学习在抓取电影内容的同时，抓取演职员表，内容简介等信息，并合并到一个页面。试试看~~作者君辛苦啦
